imports = ["language.rust"]

[devshell]
name = "satysfi-language-server"
packages = [
  "cargo-edit",
  "cargo-make",
  "cargo-watch",
  "nixpkgs-fmt",
  "rust-analyzer",
  "satysfi",
  "taplo-cli",
]

[[commands]]
package = "treefmt"
category = "formatter"
